version: "3.0"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - fefe
    volumes:
      - ./www/cms/src:/var/www/html/src
      - ./www/cms/webroot:/var/www/html/webroot
      - ./www/cms/templates:/var/www/html/templates
      - ./www/cms/logs:/var/www/html/logs
      - ./www/cms/tests:/var/www/html/tests
      - ./www/cms/config:/var/www/html/config

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - fefe
networks:
  fefe:
    driver: bridge